# For Github pages
safe: true
lsi: false

# Build settings
kramdown:
  input: GFM
highlighter: pygments

# Site settings
title: "Simplest Possible Things That Could Possibly Work"
description: > # this means to ignore newlines until "email:"
   Machine learning ideas and simulations

email: ttsuchi@mail.com
#blog logo
logo: "/assets/images/tomo_logo.png"
# blog cover
cover: "/assets/images/eng.jpg"

name: 'Tomoki Tsuchida'
author: 'Tomoki Tsuchida'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://ttsuchi.github.io"
baseurl: ""

# social icons and sharing options
#social:
#   - icon:	twitter
#     url:	https://twitter.com/dirkfabisch
#     desc: Follow me on twitter
#     share_url: http://twitter.com/share
#     share_title: ?text=
#     share_link: "&amp;url="

  # - icon:	facebook
  #   url:	https://facebook.com/ttsuchi
  #   desc:	Connect with me facebook
  #   share_url: http://www.facebook.com/sharer.php
  #   share_title: "?t="
  #   share_link: "&amp;u="
  #
  # - icon:	github
  #   url:	https://github.com/ttsuchi
  #   desc:	Fork me on github
  #   share_url:
  #   share_title:
  #   share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:

excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed